### ISSUE TITLE
Collapsible Tree

### ISSUE THREAD

**Issue by Udayqv** [tmargolis/CollapsibleTree#2]
Hi, 
I have just installed the Collapsible Tree extension on my qliksense desktop 3.2. I wanted to use more than 3 dimensions with atleast one measure, but whenever I add a fourth dimension the bubble turns white with a blue circle. Aren't we supposed to use more than 3 dimensions to show the tree structure? Also I want to show the values of the measure as a static value rather than when I hover over it. Kindly suggest the steps to be taken to achieve this.

Thanks.

**Comment by tmargolis** [comment]
Hi,
Yes, you are able to (but not required to) add more than 3 dimensions plus a measure. Each new dimension will show as another "column" in the tree depending on if your children are not also parents. If they are, then adding more fields may confuse it. Feel free to send me a link to your qvf if you'd like me to check it out.

If you'd like to always show the measure instead of just on hover, you can modify collapsibleTree.js to put the d.size in the text node rather than in the title node.

Cheers,
Todd
